/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <DEBUG_UART.h>
#include <RTC.h>
#include <DMA_1_dma.h>
#include <LED3.h>
#include <LED3_aliases.h>
#include <TimerISR_3.h>
#include <DMA_ISR.h>
#include <timer_clock_3.h>
#include <Timer_3.h>
#include <ISR_COMM_UART_RX.h>
#include <TickTimer_ISR.h>
#include <COMM_UART.h>
#include <DMA_2_dma.h>
#include <timer_clock_1.h>
#include <Tick_Timer.h>
#include <TimerISR_1.h>
#include <timer_clock.h>
#include <ISR_Switch_1.h>
#include <Timer_1.h>
#include <DMA_ISR_1.h>
#include <Button.h>
#include <Button_aliases.h>
#include <DMA_ISR_2.h>
#include <LCD.h>
#include <m_ss_pin.h>
#include <m_ss_pin_aliases.h>
#include <PWM_1.h>
#include <SPIM.h>
#include <SPIM_PVT.h>
#include <m_sclk_pin.h>
#include <m_sclk_pin_aliases.h>
#include <m_miso_pin.h>
#include <m_miso_pin_aliases.h>
#include <m_mosi_pin.h>
#include <m_mosi_pin_aliases.h>
#include <clock_3.h>
#include <DMA_3_dma.h>
#include <DMA_ISR_3.h>
#include <LED4.h>
#include <LED4_aliases.h>
#include <pin_DAC1.h>
#include <pin_DAC1_aliases.h>
#include <Pin_StimSel.h>
#include <Pin_StimSel_aliases.h>
#include <Control_Reg_StimSel.h>
#include <VDAC8_2.h>
#include <VDAC8_1.h>
#include <pin_DAC2.h>
#include <pin_DAC2_aliases.h>
#include <SwClock.h>
#include <WaveDAC8_1.h>
#include <Waveform.h>
#include <Waveform_aliases.h>
#include <DEBUG_UART_IntClock.h>
#include <COMM_UART_IntClock.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <WaveDAC8_1_DacClk.h>
#include <WaveDAC8_1_Wave1_DMA_dma.h>
#include <WaveDAC8_1_Wave2_DMA_dma.h>
#include <WaveDAC8_1_VDAC8.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

