/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Clock.h>
#include <m_miso_pin.h>
#include <m_miso_pin_aliases.h>
#include <m_sclk_pin.h>
#include <m_sclk_pin_aliases.h>
#include <SPIM.h>
#include <SPIM_PVT.h>
#include <m_ss_pin.h>
#include <m_ss_pin_aliases.h>
#include <m_mosi_pin.h>
#include <m_mosi_pin_aliases.h>
#include <UART.h>
#include <RX_pin.h>
#include <RX_pin_aliases.h>
#include <LCD_1.h>
#include <LED_B.h>
#include <LED_B_aliases.h>
#include <PWM_1.h>
#include <Clock_1.h>
#include <UART_IntClock.h>
#include <LCD_1_LCDPort.h>
#include <LCD_1_LCDPort_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

